// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApp.Data.Database;

namespace RestApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180920024837_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestApp.Data.Models.CharacterModelDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("RestApp.Data.Models.EpisodeModelDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharacterId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("RestApp.Data.Models.FriendModelDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharacterId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("RestApp.Data.Models.EpisodeModelDatabase", b =>
                {
                    b.HasOne("RestApp.Data.Models.CharacterModelDatabase", "Character")
                        .WithMany("Episodes")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("RestApp.Data.Models.FriendModelDatabase", b =>
                {
                    b.HasOne("RestApp.Data.Models.CharacterModelDatabase", "Character")
                        .WithMany("Friends")
                        .HasForeignKey("CharacterId");
                });
#pragma warning restore 612, 618
        }
    }
}
