// <auto-generated />
using System;
using ImageApp.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImageApp.Data.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20181001014338_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentImageUrl")
                        .IsRequired();

                    b.Property<string>("ContentImageUrlThumb")
                        .IsRequired();

                    b.Property<string>("ContentType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Height");

                    b.Property<long>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("ImageModel");
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelDetailsDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("ImageId");

                    b.Property<string>("Mid")
                        .IsRequired();

                    b.Property<double>("Score");

                    b.Property<double>("Topicality");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageModelDetails");
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelDetailsWebDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("EntityId");

                    b.Property<int>("ImageId");

                    b.Property<double>("Score");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageModelDetailsWeb");
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelWebMatchesDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ImageId");

                    b.Property<string>("PageTitle");

                    b.Property<string>("Url");

                    b.Property<string>("UrlImage");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageModelWebMatches");
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelDetailsDb", b =>
                {
                    b.HasOne("ImageApp.Data.Models.ImageModelDb", "Image")
                        .WithMany("ImageModelDetails")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelDetailsWebDb", b =>
                {
                    b.HasOne("ImageApp.Data.Models.ImageModelDb", "Image")
                        .WithMany("ImageModelDetailsWeb")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ImageApp.Data.Models.ImageModelWebMatchesDb", b =>
                {
                    b.HasOne("ImageApp.Data.Models.ImageModelDb", "Image")
                        .WithMany("ImageModelWebMatches")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
